import { Style } from "style.slint";

export struct Config {
    master-switch: bool,
    force: bool,
    target-temp: float,
    require-co2: bool,
    co2-target: int
}

export struct State {
    current-temp: float,
    co2: int,
    is-heating: bool
}

export global Singletons {
    in-out property<Config> config;
    in-out property<State> state;
}

export global Functions {
    public pure function darken-hc(color: color, clicked: bool, hover: bool) -> color {
        return color.darker(clicked ? Style.click-darken : hover ? Style.hover-darken : 0);
    }
}
