name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --release
    - name: 'Upload EXE'
      uses: actions/upload-artifact@v4
      with:
        name: Thermostat.exe
        path: target/release/Thermostat.exe
